site_name: etrprojections
site_url: https://sansbacon.github.io/etrprojections
site_description: python library to scrape, parse, and analyze etr projections
site_author: Eric Truett
repo_url: https://github.com/sansbacon/etrprojections

theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite
- extra
- pymdownx.superfences
- pymdownx.tabbed

nav:
- etrprojections: index.md
- features.md
- Code Reference:
    - scraper: scraper-reference.md
    - parser: parser-reference.md

